import { db } from './db';
import { Difficulty } from '@prisma/client';

async function main() {
  console.log('Start seeding...');

  const words = [
    { name: 'apple', translationToRussian: 'яблоко', difficulty: Difficulty.Easy },
    { name: 'banana', translationToRussian: 'банан', difficulty: Difficulty.Easy },
    { name: 'car', translationToRussian: 'машина', difficulty: Difficulty.Medium },
    { name: 'house', translationToRussian: 'дом', difficulty: Difficulty.Easy },
    { name: 'computer', translationToRussian: 'компьютер', difficulty: Difficulty.Medium },
    { name: 'book', translationToRussian: 'книга', difficulty: Difficulty.Easy },
    { name: 'cat', translationToRussian: 'кот', difficulty: Difficulty.Easy },
    { name: 'dog', translationToRussian: 'собака', difficulty: Difficulty.Easy },
    { name: 'tree', translationToRussian: 'дерево', difficulty: Difficulty.Easy },
    { name: 'sun', translationToRussian: 'солнце', difficulty: Difficulty.Easy },
    { name: 'water', translationToRussian: 'вода', difficulty: Difficulty.Easy },
    { name: 'food', translationToRussian: 'еда', difficulty: Difficulty.Easy },
    { name: 'moon', translationToRussian: 'луна', difficulty: Difficulty.Easy },
    { name: 'star', translationToRussian: 'звезда', difficulty: Difficulty.Easy },
    { name: 'sky', translationToRussian: 'небо', difficulty: Difficulty.Easy },
    { name: 'cloud', translationToRussian: 'облако', difficulty: Difficulty.Easy },
    { name: 'rain', translationToRussian: 'дождь', difficulty: Difficulty.Easy },
    { name: 'snow', translationToRussian: 'снег', difficulty: Difficulty.Easy },
    { name: 'wind', translationToRussian: 'ветер', difficulty: Difficulty.Easy },
    { name: 'fire', translationToRussian: 'огонь', difficulty: Difficulty.Easy },
    { name: 'earth', translationToRussian: 'земля', difficulty: Difficulty.Easy },
    { name: 'sea', translationToRussian: 'море', difficulty: Difficulty.Easy },
    { name: 'river', translationToRussian: 'река', difficulty: Difficulty.Easy },
    { name: 'mountain', translationToRussian: 'гора', difficulty: Difficulty.Easy },
    { name: 'forest', translationToRussian: 'лес', difficulty: Difficulty.Easy },
    { name: 'city', translationToRussian: 'город', difficulty: Difficulty.Easy },
    { name: 'village', translationToRussian: 'деревня', difficulty: Difficulty.Easy },
    { name: 'road', translationToRussian: 'дорога', difficulty: Difficulty.Easy },
    { name: 'bridge', translationToRussian: 'мост', difficulty: Difficulty.Easy },
    { name: 'school', translationToRussian: 'школа', difficulty: Difficulty.Easy },
    { name: 'teacher', translationToRussian: 'учитель', difficulty: Difficulty.Medium },
    { name: 'student', translationToRussian: 'студент', difficulty: Difficulty.Medium },
    { name: 'pen', translationToRussian: 'ручка', difficulty: Difficulty.Easy },
    { name: 'paper', translationToRussian: 'бумага', difficulty: Difficulty.Easy },
    { name: 'table', translationToRussian: 'стол', difficulty: Difficulty.Easy },
    { name: 'chair', translationToRussian: 'стул', difficulty: Difficulty.Easy },
    { name: 'window', translationToRussian: 'окно', difficulty: Difficulty.Easy },
    { name: 'door', translationToRussian: 'дверь', difficulty: Difficulty.Easy },
    { name: 'bed', translationToRussian: 'кровать', difficulty: Difficulty.Easy },
    { name: 'kitchen', translationToRussian: 'кухня', difficulty: Difficulty.Easy },
    { name: 'bathroom', translationToRussian: 'ванная', difficulty: Difficulty.Easy },
    { name: 'garden', translationToRussian: 'сад', difficulty: Difficulty.Easy },
    { name: 'flower', translationToRussian: 'цветок', difficulty: Difficulty.Easy },
    { name: 'grass', translationToRussian: 'трава', difficulty: Difficulty.Easy },
    { name: 'bird', translationToRussian: 'птица', difficulty: Difficulty.Easy },
    { name: 'fish', translationToRussian: 'рыба', difficulty: Difficulty.Easy },
    { name: 'horse', translationToRussian: 'лошадь', difficulty: Difficulty.Easy },
    { name: 'cow', translationToRussian: 'корова', difficulty: Difficulty.Easy },
    { name: 'sheep', translationToRussian: 'овца', difficulty: Difficulty.Easy },
    { name: 'pig', translationToRussian: 'свинья', difficulty: Difficulty.Easy },
    { name: 'chicken', translationToRussian: 'курица', difficulty: Difficulty.Easy },
    { name: 'egg', translationToRussian: 'яйцо', difficulty: Difficulty.Easy },
    { name: 'milk', translationToRussian: 'молоко', difficulty: Difficulty.Easy },
    { name: 'bread', translationToRussian: 'хлеб', difficulty: Difficulty.Easy },
    { name: 'cheese', translationToRussian: 'сыр', difficulty: Difficulty.Easy },
    { name: 'meat', translationToRussian: 'мясо', difficulty: Difficulty.Easy },
    { name: 'fruit', translationToRussian: 'фрукт', difficulty: Difficulty.Easy },
    { name: 'vegetable', translationToRussian: 'овощ', difficulty: Difficulty.Easy },
    { name: 'orange', translationToRussian: 'апельсин', difficulty: Difficulty.Easy },
    { name: 'lemon', translationToRussian: 'лимон', difficulty: Difficulty.Easy },
    { name: 'grape', translationToRussian: 'виноград', difficulty: Difficulty.Easy },
    { name: 'strawberry', translationToRussian: 'клубника', difficulty: Difficulty.Easy },
    { name: 'pineapple', translationToRussian: 'ананас', difficulty: Difficulty.Easy },
    { name: 'mango', translationToRussian: 'манго', difficulty: Difficulty.Easy },
    { name: 'tomato', translationToRussian: 'помидор', difficulty: Difficulty.Easy },
    { name: 'potato', translationToRussian: 'картофель', difficulty: Difficulty.Easy },
    { name: 'carrot', translationToRussian: 'морковь', difficulty: Difficulty.Easy },
    { name: 'onion', translationToRussian: 'лук', difficulty: Difficulty.Easy },
    { name: 'garlic', translationToRussian: 'чеснок', difficulty: Difficulty.Easy },
    { name: 'cucumber', translationToRussian: 'огурец', difficulty: Difficulty.Easy },
    { name: 'pepper', translationToRussian: 'перец', difficulty: Difficulty.Easy },
    { name: 'salt', translationToRussian: 'соль', difficulty: Difficulty.Easy },
    { name: 'sugar', translationToRussian: 'сахар', difficulty: Difficulty.Easy },
    { name: 'coffee', translationToRussian: 'кофе', difficulty: Difficulty.Easy },
    { name: 'tea', translationToRussian: 'чай', difficulty: Difficulty.Easy },
    { name: 'juice', translationToRussian: 'сок', difficulty: Difficulty.Easy },
    { name: 'wine', translationToRussian: 'вино', difficulty: Difficulty.Medium },
    { name: 'beer', translationToRussian: 'пиво', difficulty: Difficulty.Medium },
    { name: 'run', translationToRussian: 'бежать', difficulty: Difficulty.Medium },
    { name: 'jump', translationToRussian: 'прыгать', difficulty: Difficulty.Medium },
    { name: 'sing', translationToRussian: 'петь', difficulty: Difficulty.Medium },
    { name: 'dance', translationToRussian: 'танцевать', difficulty: Difficulty.Medium },
    { name: 'write', translationToRussian: 'писать', difficulty: Difficulty.Medium },
    { name: 'read', translationToRussian: 'читать', difficulty: Difficulty.Medium },
    { name: 'think', translationToRussian: 'думать', difficulty: Difficulty.Medium },
    { name: 'speak', translationToRussian: 'говорить', difficulty: Difficulty.Medium },
    { name: 'listen', translationToRussian: 'слушать', difficulty: Difficulty.Medium },
    { name: 'play', translationToRussian: 'играть', difficulty: Difficulty.Medium },
    { name: 'work', translationToRussian: 'работать', difficulty: Difficulty.Medium },
    { name: 'study', translationToRussian: 'учиться', difficulty: Difficulty.Medium },
    { name: 'learn', translationToRussian: 'изучать', difficulty: Difficulty.Medium },
    { name: 'teach', translationToRussian: 'преподавать', difficulty: Difficulty.Medium },
    { name: 'understand', translationToRussian: 'понимать', difficulty: Difficulty.Medium },
    { name: 'remember', translationToRussian: 'помнить', difficulty: Difficulty.Medium },
    { name: 'forget', translationToRussian: 'забывать', difficulty: Difficulty.Medium },
    { name: 'beautiful', translationToRussian: 'красивый', difficulty: Difficulty.Medium },
    { name: 'interesting', translationToRussian: 'интересный', difficulty: Difficulty.Medium },
    { name: 'difficult', translationToRussian: 'сложный', difficulty: Difficulty.Medium },
    { name: 'important', translationToRussian: 'важный', difficulty: Difficulty.Medium },
    { name: 'happy', translationToRussian: 'счастливый', difficulty: Difficulty.Medium },
    { name: 'sad', translationToRussian: 'грустный', difficulty: Difficulty.Medium },
    { name: 'angry', translationToRussian: 'злой', difficulty: Difficulty.Medium },
    { name: 'tired', translationToRussian: 'уставший', difficulty: Difficulty.Medium },
    { name: 'hungry', translationToRussian: 'голодный', difficulty: Difficulty.Medium },
    { name: 'thirsty', translationToRussian: 'жаждущий', difficulty: Difficulty.Medium },
    { name: 'big', translationToRussian: 'большой', difficulty: Difficulty.Easy },
    { name: 'small', translationToRussian: 'маленький', difficulty: Difficulty.Easy },
    { name: 'fast', translationToRussian: 'быстрый', difficulty: Difficulty.Medium },
    { name: 'slow', translationToRussian: 'медленный', difficulty: Difficulty.Medium },
    { name: 'hot', translationToRussian: 'горячий', difficulty: Difficulty.Easy },
    { name: 'cold', translationToRussian: 'холодный', difficulty: Difficulty.Easy },
    { name: 'new', translationToRussian: 'новый', difficulty: Difficulty.Easy },
    { name: 'old', translationToRussian: 'старый', difficulty: Difficulty.Easy },
    { name: 'good', translationToRussian: 'хороший', difficulty: Difficulty.Easy },
    { name: 'bad', translationToRussian: 'плохой', difficulty: Difficulty.Easy },
    { name: 'friend', translationToRussian: 'друг', difficulty: Difficulty.Easy },
    { name: 'family', translationToRussian: 'семья', difficulty: Difficulty.Easy },
    { name: 'love', translationToRussian: 'любовь', difficulty: Difficulty.Medium },
    { name: 'life', translationToRussian: 'жизнь', difficulty: Difficulty.Medium },
    { name: 'time', translationToRussian: 'время', difficulty: Difficulty.Medium },
    { name: 'day', translationToRussian: 'день', difficulty: Difficulty.Easy },
    { name: 'night', translationToRussian: 'ночь', difficulty: Difficulty.Easy },
    { name: 'morning', translationToRussian: 'утро', difficulty: Difficulty.Easy },
    { name: 'evening', translationToRussian: 'вечер', difficulty: Difficulty.Easy },
    { name: 'week', translationToRussian: 'неделя', difficulty: Difficulty.Easy },
    { name: 'month', translationToRussian: 'месяц', difficulty: Difficulty.Easy },
    { name: 'year', translationToRussian: 'год', difficulty: Difficulty.Easy },
    { name: 'hour', translationToRussian: 'час', difficulty: Difficulty.Easy },
    { name: 'minute', translationToRussian: 'минута', difficulty: Difficulty.Easy },
    { name: 'second', translationToRussian: 'секунда', difficulty: Difficulty.Easy },
    { name: 'summer', translationToRussian: 'лето', difficulty: Difficulty.Easy },
    { name: 'winter', translationToRussian: 'зима', difficulty: Difficulty.Easy },
    { name: 'spring', translationToRussian: 'весна', difficulty: Difficulty.Easy },
    { name: 'autumn', translationToRussian: 'осень', difficulty: Difficulty.Easy },
    { name: 'weather', translationToRussian: 'погода', difficulty: Difficulty.Medium },
    { name: 'sunny', translationToRussian: 'солнечный', difficulty: Difficulty.Medium },
    { name: 'cloudy', translationToRussian: 'облачный', difficulty: Difficulty.Medium },
    { name: 'rainy', translationToRussian: 'дождливый', difficulty: Difficulty.Medium },
    { name: 'snowy', translationToRussian: 'снежный', difficulty: Difficulty.Medium },
    { name: 'windy', translationToRussian: 'ветреный', difficulty: Difficulty.Medium },
    { name: 'warm', translationToRussian: 'тёплый', difficulty: Difficulty.Medium },
    { name: 'cool', translationToRussian: 'прохладный', difficulty: Difficulty.Medium },
    { name: 'phone', translationToRussian: 'телефон', difficulty: Difficulty.Easy },
    { name: 'television', translationToRussian: 'телевизор', difficulty: Difficulty.Easy },
    { name: 'internet', translationToRussian: 'интернет', difficulty: Difficulty.Medium },
    { name: 'music', translationToRussian: 'музыка', difficulty: Difficulty.Easy },
    { name: 'movie', translationToRussian: 'фильм', difficulty: Difficulty.Easy },
    { name: 'game', translationToRussian: 'игра', difficulty: Difficulty.Easy },
    { name: 'sport', translationToRussian: 'спорт', difficulty: Difficulty.Easy },
    { name: 'football', translationToRussian: 'футбол', difficulty: Difficulty.Easy },
    { name: 'basketball', translationToRussian: 'баскетбол', difficulty: Difficulty.Easy },
    { name: 'tennis', translationToRussian: 'теннис', difficulty: Difficulty.Easy },
    { name: 'swimming', translationToRussian: 'плавание', difficulty: Difficulty.Medium },
    { name: 'bicycle', translationToRussian: 'велосипед', difficulty: Difficulty.Easy },
    { name: 'train', translationToRussian: 'поезд', difficulty: Difficulty.Easy },
    { name: 'bus', translationToRussian: 'автобус', difficulty: Difficulty.Easy },
    { name: 'airplane', translationToRussian: 'самолёт', difficulty: Difficulty.Easy },
    { name: 'boat', translationToRussian: 'лодка', difficulty: Difficulty.Easy },
    { name: 'travel', translationToRussian: 'путешествовать', difficulty: Difficulty.Medium },
    { name: 'hotel', translationToRussian: 'отель', difficulty: Difficulty.Easy },
    { name: 'beach', translationToRussian: 'пляж', difficulty: Difficulty.Easy },
    { name: 'park', translationToRussian: 'парк', difficulty: Difficulty.Easy },
    { name: 'museum', translationToRussian: 'музей', difficulty: Difficulty.Medium },
    { name: 'art', translationToRussian: 'искусство', difficulty: Difficulty.Medium },
    { name: 'history', translationToRussian: 'история', difficulty: Difficulty.Medium },
    { name: 'science', translationToRussian: 'наука', difficulty: Difficulty.Medium },
    { name: 'math', translationToRussian: 'математика', difficulty: Difficulty.Medium },
    { name: 'language', translationToRussian: 'язык', difficulty: Difficulty.Medium },
    { name: 'culture', translationToRussian: 'культура', difficulty: Difficulty.Medium },
    { name: 'tradition', translationToRussian: 'традиция', difficulty: Difficulty.Medium },
    { name: 'festival', translationToRussian: 'фестиваль', difficulty: Difficulty.Medium },
    { name: 'holiday', translationToRussian: 'праздник', difficulty: Difficulty.Easy },
    { name: 'party', translationToRussian: 'вечеринка', difficulty: Difficulty.Easy },
    { name: 'gift', translationToRussian: 'подарок', difficulty: Difficulty.Easy },
    { name: 'cake', translationToRussian: 'торт', difficulty: Difficulty.Easy },
    { name: 'candle', translationToRussian: 'свеча', difficulty: Difficulty.Easy },
    { name: 'smile', translationToRussian: 'улыбка', difficulty: Difficulty.Easy },
    { name: 'laugh', translationToRussian: 'смех', difficulty: Difficulty.Medium },
    { name: 'cry', translationToRussian: 'плач', difficulty: Difficulty.Medium },
    { name: 'dream', translationToRussian: 'мечта', difficulty: Difficulty.Medium },
    { name: 'hope', translationToRussian: 'надежда', difficulty: Difficulty.Medium },
    { name: 'fear', translationToRussian: 'страх', difficulty: Difficulty.Medium },
    { name: 'joy', translationToRussian: 'радость', difficulty: Difficulty.Medium },
    { name: 'peace', translationToRussian: 'мир', difficulty: Difficulty.Medium },
    { name: 'war', translationToRussian: 'война', difficulty: Difficulty.Medium },
    { name: 'health', translationToRussian: 'здоровье', difficulty: Difficulty.Medium },
    { name: 'money', translationToRussian: 'деньги', difficulty: Difficulty.Medium },
    { name: 'job', translationToRussian: 'работа', difficulty: Difficulty.Medium },
    { name: 'business', translationToRussian: 'бизнес', difficulty: Difficulty.Medium },
    { name: 'market', translationToRussian: 'рынок', difficulty: Difficulty.Medium },
    { name: 'shop', translationToRussian: 'магазин', difficulty: Difficulty.Easy },
    { name: 'price', translationToRussian: 'цена', difficulty: Difficulty.Medium },
    { name: 'buy', translationToRussian: 'покупать', difficulty: Difficulty.Medium },
    { name: 'sell', translationToRussian: 'продавать', difficulty: Difficulty.Medium },
    { name: 'idea', translationToRussian: 'идея', difficulty: Difficulty.Medium },
    { name: 'plan', translationToRussian: 'план', difficulty: Difficulty.Medium },
    { name: 'goal', translationToRussian: 'цель', difficulty: Difficulty.Medium },
    { name: 'success', translationToRussian: 'успех', difficulty: Difficulty.Medium },
    { name: 'failure', translationToRussian: 'неудача', difficulty: Difficulty.Medium },
    { name: 'change', translationToRussian: 'изменение', difficulty: Difficulty.Medium },
    { name: 'future', translationToRussian: 'будущее', difficulty: Difficulty.Medium },
    { name: 'past', translationToRussian: 'прошлое', difficulty: Difficulty.Medium },
    { name: 'present', translationToRussian: 'настоящее', difficulty: Difficulty.Medium }
  ];

  for (const word of words) {
    await db.word.create({
      data: word,
    });
    console.log(`Created word with name: ${word.name}`);
  }

  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });

